// 本文件由 .ref/gen_opcode_table.js 从 fogleman/nes 的 cpu.go 生成，不要手改。
//
// 6502 的 opcode 矩阵：每行 16 个操作码，取值 = 操作 + 寻址模式 + 基础周期数。
// 基础周期数**不含**跨页附加周期（那部分在 Cpu.ResolveAddress 里按需加）。
//
// 三个来源互相核对过：fogleman/nes 的 instructionModes/instructionCycles、
// jsnes 的 OPCODE_TABLE、以及 nesdev 的官方指令表。
// 非官方指令里那些 "NOP" 变体按 NOP 处理（很多游戏会用它们），其余标成 Illegal。

namespace GodotNes.Core;

public static class OpcodeTable
{
	/// <summary>256 项 opcode 定义，索引就是操作码本身。</summary>
	public static readonly Op[] Ops =
	{
		// $00-$0F
		new(Instruction.Brk, AddrMode.Imp, 7), new(Instruction.Ora, AddrMode.IndX, 6), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndX, 8), new(Instruction.Nop, AddrMode.Zp, 3), new(Instruction.Ora, AddrMode.Zp, 3), new(Instruction.Asl, AddrMode.Zp, 5), new(Instruction.Illegal, AddrMode.Zp, 5), new(Instruction.Php, AddrMode.Imp, 3), new(Instruction.Ora, AddrMode.Imm, 2), new(Instruction.Asl, AddrMode.Acc, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Nop, AddrMode.Abs, 4), new(Instruction.Ora, AddrMode.Abs, 4), new(Instruction.Asl, AddrMode.Abs, 6), new(Instruction.Illegal, AddrMode.Abs, 6),
		// $10-$1F
		new(Instruction.Bpl, AddrMode.Rel, 2), new(Instruction.Ora, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 8), new(Instruction.Nop, AddrMode.ZpX, 4), new(Instruction.Ora, AddrMode.ZpX, 4), new(Instruction.Asl, AddrMode.ZpX, 6), new(Instruction.Illegal, AddrMode.ZpX, 6), new(Instruction.Clc, AddrMode.Imp, 2), new(Instruction.Ora, AddrMode.AbsY, 4), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 7), new(Instruction.Nop, AddrMode.AbsX, 4), new(Instruction.Ora, AddrMode.AbsX, 4), new(Instruction.Asl, AddrMode.AbsX, 7), new(Instruction.Illegal, AddrMode.AbsX, 7),
		// $20-$2F
		new(Instruction.Jsr, AddrMode.Abs, 6), new(Instruction.And, AddrMode.IndX, 6), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndX, 8), new(Instruction.Bit, AddrMode.Zp, 3), new(Instruction.And, AddrMode.Zp, 3), new(Instruction.Rol, AddrMode.Zp, 5), new(Instruction.Illegal, AddrMode.Zp, 5), new(Instruction.Plp, AddrMode.Imp, 4), new(Instruction.And, AddrMode.Imm, 2), new(Instruction.Rol, AddrMode.Acc, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Bit, AddrMode.Abs, 4), new(Instruction.And, AddrMode.Abs, 4), new(Instruction.Rol, AddrMode.Abs, 6), new(Instruction.Illegal, AddrMode.Abs, 6),
		// $30-$3F
		new(Instruction.Bmi, AddrMode.Rel, 2), new(Instruction.And, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 8), new(Instruction.Nop, AddrMode.ZpX, 4), new(Instruction.And, AddrMode.ZpX, 4), new(Instruction.Rol, AddrMode.ZpX, 6), new(Instruction.Illegal, AddrMode.ZpX, 6), new(Instruction.Sec, AddrMode.Imp, 2), new(Instruction.And, AddrMode.AbsY, 4), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 7), new(Instruction.Nop, AddrMode.AbsX, 4), new(Instruction.And, AddrMode.AbsX, 4), new(Instruction.Rol, AddrMode.AbsX, 7), new(Instruction.Illegal, AddrMode.AbsX, 7),
		// $40-$4F
		new(Instruction.Rti, AddrMode.Imp, 6), new(Instruction.Eor, AddrMode.IndX, 6), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndX, 8), new(Instruction.Nop, AddrMode.Zp, 3), new(Instruction.Eor, AddrMode.Zp, 3), new(Instruction.Lsr, AddrMode.Zp, 5), new(Instruction.Illegal, AddrMode.Zp, 5), new(Instruction.Pha, AddrMode.Imp, 3), new(Instruction.Eor, AddrMode.Imm, 2), new(Instruction.Lsr, AddrMode.Acc, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Jmp, AddrMode.Abs, 3), new(Instruction.Eor, AddrMode.Abs, 4), new(Instruction.Lsr, AddrMode.Abs, 6), new(Instruction.Illegal, AddrMode.Abs, 6),
		// $50-$5F
		new(Instruction.Bvc, AddrMode.Rel, 2), new(Instruction.Eor, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 8), new(Instruction.Nop, AddrMode.ZpX, 4), new(Instruction.Eor, AddrMode.ZpX, 4), new(Instruction.Lsr, AddrMode.ZpX, 6), new(Instruction.Illegal, AddrMode.ZpX, 6), new(Instruction.Cli, AddrMode.Imp, 2), new(Instruction.Eor, AddrMode.AbsY, 4), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 7), new(Instruction.Nop, AddrMode.AbsX, 4), new(Instruction.Eor, AddrMode.AbsX, 4), new(Instruction.Lsr, AddrMode.AbsX, 7), new(Instruction.Illegal, AddrMode.AbsX, 7),
		// $60-$6F
		new(Instruction.Rts, AddrMode.Imp, 6), new(Instruction.Adc, AddrMode.IndX, 6), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndX, 8), new(Instruction.Nop, AddrMode.Zp, 3), new(Instruction.Adc, AddrMode.Zp, 3), new(Instruction.Ror, AddrMode.Zp, 5), new(Instruction.Illegal, AddrMode.Zp, 5), new(Instruction.Pla, AddrMode.Imp, 4), new(Instruction.Adc, AddrMode.Imm, 2), new(Instruction.Ror, AddrMode.Acc, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Jmp, AddrMode.Ind, 5), new(Instruction.Adc, AddrMode.Abs, 4), new(Instruction.Ror, AddrMode.Abs, 6), new(Instruction.Illegal, AddrMode.Abs, 6),
		// $70-$7F
		new(Instruction.Bvs, AddrMode.Rel, 2), new(Instruction.Adc, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 8), new(Instruction.Nop, AddrMode.ZpX, 4), new(Instruction.Adc, AddrMode.ZpX, 4), new(Instruction.Ror, AddrMode.ZpX, 6), new(Instruction.Illegal, AddrMode.ZpX, 6), new(Instruction.Sei, AddrMode.Imp, 2), new(Instruction.Adc, AddrMode.AbsY, 4), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 7), new(Instruction.Nop, AddrMode.AbsX, 4), new(Instruction.Adc, AddrMode.AbsX, 4), new(Instruction.Ror, AddrMode.AbsX, 7), new(Instruction.Illegal, AddrMode.AbsX, 7),
		// $80-$8F
		new(Instruction.Nop, AddrMode.Imm, 2), new(Instruction.Sta, AddrMode.IndX, 6), new(Instruction.Nop, AddrMode.Imm, 2), new(Instruction.Illegal, AddrMode.IndX, 6), new(Instruction.Sty, AddrMode.Zp, 3), new(Instruction.Sta, AddrMode.Zp, 3), new(Instruction.Stx, AddrMode.Zp, 3), new(Instruction.Illegal, AddrMode.Zp, 3), new(Instruction.Dey, AddrMode.Imp, 2), new(Instruction.Nop, AddrMode.Imm, 2), new(Instruction.Txa, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Sty, AddrMode.Abs, 4), new(Instruction.Sta, AddrMode.Abs, 4), new(Instruction.Stx, AddrMode.Abs, 4), new(Instruction.Illegal, AddrMode.Abs, 4),
		// $90-$9F
		new(Instruction.Bcc, AddrMode.Rel, 2), new(Instruction.Sta, AddrMode.IndY, 6), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 6), new(Instruction.Sty, AddrMode.ZpX, 4), new(Instruction.Sta, AddrMode.ZpX, 4), new(Instruction.Stx, AddrMode.ZpY, 4), new(Instruction.Illegal, AddrMode.ZpY, 4), new(Instruction.Tya, AddrMode.Imp, 2), new(Instruction.Sta, AddrMode.AbsY, 5), new(Instruction.Txs, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 5), new(Instruction.Illegal, AddrMode.AbsX, 5), new(Instruction.Sta, AddrMode.AbsX, 5), new(Instruction.Illegal, AddrMode.AbsY, 5), new(Instruction.Illegal, AddrMode.AbsY, 5),
		// $A0-$AF
		new(Instruction.Ldy, AddrMode.Imm, 2), new(Instruction.Lda, AddrMode.IndX, 6), new(Instruction.Ldx, AddrMode.Imm, 2), new(Instruction.Illegal, AddrMode.IndX, 6), new(Instruction.Ldy, AddrMode.Zp, 3), new(Instruction.Lda, AddrMode.Zp, 3), new(Instruction.Ldx, AddrMode.Zp, 3), new(Instruction.Illegal, AddrMode.Zp, 3), new(Instruction.Tay, AddrMode.Imp, 2), new(Instruction.Lda, AddrMode.Imm, 2), new(Instruction.Tax, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Ldy, AddrMode.Abs, 4), new(Instruction.Lda, AddrMode.Abs, 4), new(Instruction.Ldx, AddrMode.Abs, 4), new(Instruction.Illegal, AddrMode.Abs, 4),
		// $B0-$BF
		new(Instruction.Bcs, AddrMode.Rel, 2), new(Instruction.Lda, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 5), new(Instruction.Ldy, AddrMode.ZpX, 4), new(Instruction.Lda, AddrMode.ZpX, 4), new(Instruction.Ldx, AddrMode.ZpY, 4), new(Instruction.Illegal, AddrMode.ZpY, 4), new(Instruction.Clv, AddrMode.Imp, 2), new(Instruction.Lda, AddrMode.AbsY, 4), new(Instruction.Tsx, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 4), new(Instruction.Ldy, AddrMode.AbsX, 4), new(Instruction.Lda, AddrMode.AbsX, 4), new(Instruction.Ldx, AddrMode.AbsY, 4), new(Instruction.Illegal, AddrMode.AbsY, 4),
		// $C0-$CF
		new(Instruction.Cpy, AddrMode.Imm, 2), new(Instruction.Cmp, AddrMode.IndX, 6), new(Instruction.Nop, AddrMode.Imm, 2), new(Instruction.Illegal, AddrMode.IndX, 8), new(Instruction.Cpy, AddrMode.Zp, 3), new(Instruction.Cmp, AddrMode.Zp, 3), new(Instruction.Dec, AddrMode.Zp, 5), new(Instruction.Illegal, AddrMode.Zp, 5), new(Instruction.Iny, AddrMode.Imp, 2), new(Instruction.Cmp, AddrMode.Imm, 2), new(Instruction.Dex, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.Imm, 2), new(Instruction.Cpy, AddrMode.Abs, 4), new(Instruction.Cmp, AddrMode.Abs, 4), new(Instruction.Dec, AddrMode.Abs, 6), new(Instruction.Illegal, AddrMode.Abs, 6),
		// $D0-$DF
		new(Instruction.Bne, AddrMode.Rel, 2), new(Instruction.Cmp, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 8), new(Instruction.Nop, AddrMode.ZpX, 4), new(Instruction.Cmp, AddrMode.ZpX, 4), new(Instruction.Dec, AddrMode.ZpX, 6), new(Instruction.Illegal, AddrMode.ZpX, 6), new(Instruction.Cld, AddrMode.Imp, 2), new(Instruction.Cmp, AddrMode.AbsY, 4), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 7), new(Instruction.Nop, AddrMode.AbsX, 4), new(Instruction.Cmp, AddrMode.AbsX, 4), new(Instruction.Dec, AddrMode.AbsX, 7), new(Instruction.Illegal, AddrMode.AbsX, 7),
		// $E0-$EF
		new(Instruction.Cpx, AddrMode.Imm, 2), new(Instruction.Sbc, AddrMode.IndX, 6), new(Instruction.Nop, AddrMode.Imm, 2), new(Instruction.Illegal, AddrMode.IndX, 8), new(Instruction.Cpx, AddrMode.Zp, 3), new(Instruction.Sbc, AddrMode.Zp, 3), new(Instruction.Inc, AddrMode.Zp, 5), new(Instruction.Illegal, AddrMode.Zp, 5), new(Instruction.Inx, AddrMode.Imp, 2), new(Instruction.Sbc, AddrMode.Imm, 2), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Sbc, AddrMode.Imm, 2), new(Instruction.Cpx, AddrMode.Abs, 4), new(Instruction.Sbc, AddrMode.Abs, 4), new(Instruction.Inc, AddrMode.Abs, 6), new(Instruction.Illegal, AddrMode.Abs, 6),
		// $F0-$FF
		new(Instruction.Beq, AddrMode.Rel, 2), new(Instruction.Sbc, AddrMode.IndY, 5), new(Instruction.Illegal, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.IndY, 8), new(Instruction.Nop, AddrMode.ZpX, 4), new(Instruction.Sbc, AddrMode.ZpX, 4), new(Instruction.Inc, AddrMode.ZpX, 6), new(Instruction.Illegal, AddrMode.ZpX, 6), new(Instruction.Sed, AddrMode.Imp, 2), new(Instruction.Sbc, AddrMode.AbsY, 4), new(Instruction.Nop, AddrMode.Imp, 2), new(Instruction.Illegal, AddrMode.AbsY, 7), new(Instruction.Nop, AddrMode.AbsX, 4), new(Instruction.Sbc, AddrMode.AbsX, 4), new(Instruction.Inc, AddrMode.AbsX, 7), new(Instruction.Illegal, AddrMode.AbsX, 7),
	};

	/// <summary>取某个操作码的定义。</summary>
	public static ref readonly Op Get(byte opcode) => ref Ops[opcode];
}
